services:
  traefik:
    image: "traefik"
    restart: unless-stopped
    command:
      - "--api=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true"
      - "--certificatesresolvers.mytlschallenge.acme.email=${SSL_EMAIL}"
      - "--certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - traefik_data:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro

  mixpost:
    image: inovector/mixpost:latest
    env_file:
      - .env
    labels:
      - traefik.enable=true
      - traefik.http.routers.mixpost.rule=Host(`mixpost.imvickykumar999.online`)
      - traefik.http.services.mixpost.loadbalancer.server.port=80
      - traefik.http.routers.mixpost.tls=true
      - traefik.http.routers.mixpost.entrypoints=web,websecure
      - traefik.http.routers.mixpost.tls.certresolver=mytlschallenge
      - traefik.http.middlewares.mixpost.headers.SSLRedirect=true
      - traefik.http.middlewares.mixpost.headers.STSSeconds=315360000
      - traefik.http.middlewares.mixpost.headers.browserXSSFilter=true
      - traefik.http.middlewares.mixpost.headers.contentTypeNosniff=true
      - traefik.http.middlewares.mixpost.headers.forceSTSHeader=true
      - traefik.http.middlewares.mixpost.headers.SSLHost=mixpost.imvickykumar999.online
      - traefik.http.middlewares.mixpost.headers.STSIncludeSubdomains=true
      - traefik.http.middlewares.mixpost.headers.STSPreload=true
      - traefik.http.routers.mixpost.middlewares=mixpost@docker
    volumes:
      - storage:/var/www/html/storage/app
      - logs:/var/www/html/storage/logs
    depends_on:
      - mysql
      - redis
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: **********
      MYSQL_DATABASE: mixpost_db
      MYSQL_USER: mixpost_user
      MYSQL_PASSWORD: **********
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped

  redis:
    image: 'redis:latest'
    command: redis-server --appendonly yes --replica-read-only no
    volumes:
      - 'redis:/data'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s
    restart: unless-stopped

volumes:
  traefik_data:
  mysql:
  redis:
  storage:
  logs:
