# Generated by Django 5.2.5 on 2025-08-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtask',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='media',
            field=models.FileField(blank=True, help_text='Upload image/video/gif', null=True, upload_to='scheduled_media/'),
        ),
    ]
