# Generated by Django 5.2.5 on 2025-08-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0002_scheduledtask_caption_scheduledtask_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtask',
            name='url_generated',
            field=models.URLField(blank=True, help_text='Mastodon URL after successful post', null=True),
        ),
    ]
